-- Cadastro dos 3 produtos da Linha SC – Inspeção Avançada (BT-SC300A, BT-SC500-A, BT-SC600).
-- Modelo: BT-X300. Só insere: se já existir produto com o mesmo id, nada é sobrescrito.
-- Imagens: placeholder do site até as fotos serem enviadas pelo /admin.
begin;

-- camera-termografica-bt-sc300a
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-sc300a',
  'Câmera Termográfica com Lentes Intercambiáveis 384x288 — BT-SC300A',
  'Câmera termográfica BT-SC300A com resolução 384x288, NETD <40mK e lentes intercambiáveis de 6° a 48°, para inspeções de perto e à distância.
Foco manual, tela touch de 4,3" ou 5", câmera 5MP com LED, Wi-Fi, HDMI e medição de -20°C a 410°C, com faixa opcional até 2.000°C.',
  'SC - Inspeção Avançada', '/placeholder.svg',
  '384x288', '1,30 mrad (lente 24°)', '<40mK', '-20°C a 410°C', true,
  'Câmera Termográfica 384x288 com Lentes BT-SC300A | Borotec',
  'Câmera termográfica BT-SC300A: 384x288, NETD <40mK, lentes opcionais de 6° a 48°, tela touch e câmera 5MP. Mede até 410°C. Solicite orçamento!',
  '{"ip": "Faixa", "cable": "Resolução IR", "probe": "IFOV", "camera": "NETD"}'::jsonb,
  now() + interval '0 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-sc300a',
  'A BT-SC300A é a porta de entrada da Linha SC para equipes que precisam de versatilidade em campo. Com resolução de 384x288, NETD <40mK e lente padrão de 24°, ela aceita lentes opcionais de 48° para áreas amplas e de 12° ou 6° para alvos distantes. O foco manual, a câmera de 5MP com LED, a mira laser e a fusão de imagens ajudam a localizar a falha com exatidão. Mede de -20°C a 410°C, com faixa opcional até 2.000°C, e oferece vídeo radiométrico, saída HDMI, Wi-Fi, 4G e GPS opcionais, proteção IP54 e software para laudos.',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "384x288", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "1,30 / 2,26 / 0,68 / 0,34 mrad", "filter": true, "filter_value": "1,30 mrad"}, {"label": "Foco", "value": "Manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,5 / 1 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo ou veicular"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,09 kg (com bateria)"}, {"label": "Dimensões", "value": "260x135x136 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "4,3\" ou 5\", legível sob sol, 480x272 / 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "IR, visível, PIP, fusão e MIF"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com as lentes de 12° e 6°.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.', 'Energia Solar: identificação de células defeituosas e hot spots em usinas fotovoltaicas.', 'Laudos e Perícias Técnicas: imagens e vídeos radiométricos com todos os dados de temperatura, analisados no software para relatórios.']::text[],
  '[{"question": "Qual a diferença entre a BT-SC300A, a BT-SC500-A e a BT-SC600?", "answer": "A resolução. A BT-SC300A tem 384x288, a BT-SC500-A tem 480x360 e a BT-SC600 tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Para que servem as lentes opcionais?", "answer": "A lente de 48° amplia o campo de visão para inspecionar áreas grandes de perto, como painéis inteiros. As lentes de 12° e 6° aproximam a imagem para medir alvos distantes, como isoladores em subestações e conexões em linhas de transmissão."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, e acompanham software de análise para geração de relatórios."}, {"question": "Como transfiro as imagens?", "answer": "Por Wi-Fi, saída HDMI, cartão SD de 32 GB ou 4G opcional, com visualização em nuvem."}]'::jsonb
)
on conflict (product_id) do nothing;

-- camera-termografica-bt-sc500-a
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-sc500-a',
  'Câmera Termográfica com Lentes Intercambiáveis 480x360 — BT-SC500-A',
  'Câmera termográfica BT-SC500-A com resolução 480x360, NETD <40mK, IFOV de 0,92 mrad e lentes intercambiáveis de 6° a 48°.
Foco manual, tela touch de 5" legível sob sol, câmera 5MP com LED, Wi-Fi, HDMI e medição de -20°C a 410°C, com faixa opcional até 2.000°C.',
  'SC - Inspeção Avançada', '/placeholder.svg',
  '480x360', '0,92 mrad (lente 24°)', '<40mK', '-20°C a 410°C', true,
  'Câmera Termográfica 480x360 com Lentes BT-SC500-A | Borotec',
  'Câmera termográfica BT-SC500-A: 480x360, NETD <40mK, IFOV 0,92 mrad, tela de 5" e lentes de 6° a 48°. Mais detalhe à distância. Peça orçamento!',
  '{"ip": "Faixa", "cable": "Resolução IR", "probe": "IFOV", "camera": "NETD"}'::jsonb,
  now() + interval '1 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-sc500-a',
  'A BT-SC500-A é o modelo intermediário da Linha SC, com cerca de 56% mais pixels térmicos que a BT-SC300A. Com resolução de 480x360, NETD <40mK e IFOV de 0,92 mrad, ela entrega mais detalhe em componentes pequenos e alvos distantes. A lente padrão de 24° pode ser trocada pelas opcionais de 48°, 12° ou 6°, e a tela touch de 5" com 800x480 facilita a análise ainda em campo. Mede de -20°C a 410°C, com faixa opcional até 2.000°C, grava vídeo radiométrico, tem saída HDMI, Wi-Fi, proteção IP54 e software de análise para relatórios técnicos.',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "480x360", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "0,92 / 1,87 / 0,46 / 0,23 mrad", "filter": true, "filter_value": "0,92 mrad"}, {"label": "Foco", "value": "Manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,5 / 2 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo ou veicular"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,09 kg (com bateria)"}, {"label": "Dimensões", "value": "260x135x136 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "5\", legível sob sol, 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "IR, visível, PIP, fusão e MIF"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com as lentes de 12° e 6°.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.', 'Energia Solar: identificação de células defeituosas e hot spots em usinas fotovoltaicas.', 'Laudos e Perícias Técnicas: imagens e vídeos radiométricos com todos os dados de temperatura, analisados no software para relatórios.']::text[],
  '[{"question": "Qual a diferença entre a BT-SC300A, a BT-SC500-A e a BT-SC600?", "answer": "A resolução. A BT-SC300A tem 384x288, a BT-SC500-A tem 480x360 e a BT-SC600 tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Para que servem as lentes opcionais?", "answer": "A lente de 48° amplia o campo de visão para inspecionar áreas grandes de perto, como painéis inteiros. As lentes de 12° e 6° aproximam a imagem para medir alvos distantes, como isoladores em subestações e conexões em linhas de transmissão."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, e acompanham software de análise para geração de relatórios."}, {"question": "Como transfiro as imagens?", "answer": "Por Wi-Fi, saída HDMI, cartão SD de 32 GB ou 4G opcional, com visualização em nuvem."}]'::jsonb
)
on conflict (product_id) do nothing;

-- camera-termografica-bt-sc600
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-sc600',
  'Câmera Termográfica de Alta Resolução 640x512 com Lentes Intercambiáveis — BT-SC600',
  'Câmera termográfica BT-SC600 com alta resolução de 640x512, NETD <40mK, IFOV de 0,66 mrad e lentes intercambiáveis de 6° a 48°.
Com a lente de 6°, chega a 0,16 mrad para alvos a longa distância. Tela touch de 5", câmera 5MP, Wi-Fi, HDMI e faixa opcional até 2.000°C.',
  'SC - Inspeção Avançada', '/placeholder.svg',
  '640x512', '0,66 mrad (lente 24°)', '<40mK', '-20°C a 410°C', true,
  'Câmera Termográfica 640x512 com Lentes BT-SC600 | Borotec',
  'Câmera termográfica BT-SC600: 640x512, NETD <40mK, IFOV 0,66 mrad e lentes de 6° a 48° para alvos a longa distância. Solicite orçamento!',
  '{"ip": "Faixa", "cable": "Resolução IR", "probe": "IFOV", "camera": "NETD"}'::jsonb,
  now() + interval '2 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-sc600',
  'A BT-SC600 é o modelo topo da Linha SC, para inspeções que exigem o máximo de detalhe a qualquer distância. Com 640x512 pixels, NETD <40mK e IFOV de 0,66 mrad na lente padrão, ela chega a 0,16 mrad com a lente opcional de 6°, o que permite medir com precisão isoladores, conexões e cabos em subestações e linhas de transmissão. A tela touch de 5", a câmera de 5MP com LED e a fusão de imagens deixam os registros nítidos e fáceis de interpretar nos laudos. Mede de -20°C a 410°C, com faixa opcional até 2.000°C, e oferece vídeo radiométrico, HDMI, Wi-Fi, 4G e GPS opcionais e proteção IP54.',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "640x512", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "0,66 / 1,39 / 0,33 / 0,16 mrad", "filter": true, "filter_value": "0,66 mrad"}, {"label": "Foco", "value": "Manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,5 / 2 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo ou veicular"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,09 kg (com bateria)"}, {"label": "Dimensões", "value": "260x135x136 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "5\", legível sob sol, 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "IR, visível, PIP, fusão e MIF"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com as lentes de 12° e 6°.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.', 'Energia Solar: identificação de células defeituosas e hot spots em usinas fotovoltaicas.', 'Laudos e Perícias Técnicas: imagens e vídeos radiométricos com todos os dados de temperatura, analisados no software para relatórios.']::text[],
  '[{"question": "Qual a diferença entre a BT-SC300A, a BT-SC500-A e a BT-SC600?", "answer": "A resolução. A BT-SC300A tem 384x288, a BT-SC500-A tem 480x360 e a BT-SC600 tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Para que servem as lentes opcionais?", "answer": "A lente de 48° amplia o campo de visão para inspecionar áreas grandes de perto, como painéis inteiros. As lentes de 12° e 6° aproximam a imagem para medir alvos distantes, como isoladores em subestações e conexões em linhas de transmissão."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, e acompanham software de análise para geração de relatórios."}, {"question": "Como transfiro as imagens?", "answer": "Por Wi-Fi, saída HDMI, cartão SD de 32 GB ou 4G opcional, com visualização em nuvem."}]'::jsonb
)
on conflict (product_id) do nothing;

commit;
