-- Cadastro dos 3 produtos da Linha SC-B – Inspeção de Precisão (BT-300B, BT-500B, BT-600B).
-- Modelo: BT-X300 / Linha SC. Só insere: se já existir produto com o mesmo id, nada é sobrescrito.
-- Imagens: placeholder do site até as fotos serem enviadas pelo /admin.
begin;

-- camera-termografica-bt-300b
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-300b',
  'Câmera Termográfica com Foco Automático e Laser 384x288 — BT-300B',
  'Câmera termográfica BT-300B com resolução 384x288, foco automático, medição de distância a laser até 40 m e lentes intercambiáveis de 6° a 48°.
NETD <40mK, reconhecimento automático de lente, tela touch, câmera 5MP com LED, anotação por voz e medição de -20°C a 410°C, com opcional até 2.000°C.',
  'Linha SC-B - Inspeção de Precisão', '/placeholder.svg',
  'Automático', '384x288', 'Distância até 40 m', '<40mK', true,
  'Câmera Termográfica Autofoco 384x288 BT-300B | Borotec',
  'Câmera termográfica BT-300B: 384x288, foco automático, medição de distância a laser até 40m e lentes de 6° a 48°. NETD <40mK. Solicite orçamento!',
  '{"probe": "Resolução IR", "cable": "Foco", "camera": "Laser", "ip": "NETD"}'::jsonb,
  now() + interval '0 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-300b',
  'A BT-300B é a porta de entrada da Linha B para termografistas que querem agilidade e precisão em cada registro. Com resolução de 384x288 e NETD <40mK, ela tem foco em três modos (automático, elétrico e manual), que garante imagens nítidas sem ajuste demorado. O laser mede a distância até o alvo em até 40 m e mostra o ponto de medição na imagem infravermelha. A lente padrão de 24° pode ser trocada pelas opcionais de 48°, 12° ou 6°, e a câmera reconhece a nova lente automaticamente. Com anotação por voz de 60 segundos e textos predefinidos salvos junto com a imagem, os laudos ficam prontos mais rápido. Mede de -20°C a 410°C, com faixa opcional até 2.000°C.

Prefere foco manual e um equipamento mais leve? [Conheça a Linha A.](/termografia/linha-sc-a/inspecao-avancada)',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "384x288", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "Reconhecimento de lente", "value": "Automático após a troca"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "1,30 / 2,26 / 0,68 / 0,34 mrad", "filter": true, "filter_value": "1,30 mrad"}, {"label": "Foco", "value": "Automático, elétrico e manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,3 / 1 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo, adaptador AC ou carregador veicular"}, {"label": "Economia de energia", "value": "Modo de suspensão"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,23 kg (com bateria)"}, {"label": "Dimensões", "value": "279x135x147 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}, {"label": "Medição de distância a laser", "value": "Até 40 m"}, {"label": "Alinhamento do laser", "value": "Posição exibida automaticamente na imagem infravermelha"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "4,3\" ou 5\", legível sob sol, 480x272 / 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "Infravermelho, visível, PIP, fusão e IMIX"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}, {"label": "Anotação por voz", "value": "60 segundos, salva com a imagem"}, {"label": "Anotação de texto", "value": "Textos predefinidos, salvos com a imagem"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}, {"title": "Software", "icon_name": "Cpu", "rows": [{"label": "Software de análise", "value": "Windows 7 ou superior, com análise e geração de relatórios"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com foco automático e lentes de 12° e 6°.', 'Laudos Termográficos e Inspeções em Série: foco automático, distância medida a laser e anotação por voz agilizam inspeções com muitos pontos e a produção de laudos.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.']::text[],
  '[{"question": "Qual a diferença entre a BT-300B, a BT-500B e a BT-600B?", "answer": "A resolução. A BT-300B tem 384x288, a BT-500B tem 480x360 e a BT-600B tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Qual a diferença entre a Linha B e a Linha A?", "answer": "As resoluções e as lentes são as mesmas. A Linha B tem foco automático, medição de distância a laser até 40 m, reconhecimento automático de lente e anotação por voz e texto. A Linha A tem foco manual e é mais leve (1,09 kg contra 1,23 kg)."}, {"question": "Para que serve a medição de distância a laser?", "answer": "O laser mede a distância até o alvo em até 40 m e mostra o ponto medido na imagem infravermelha. Assim o técnico sabe exatamente onde e a que distância cada registro foi feito."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, com anotações de voz e texto, e acompanham software para Windows com análise e geração de relatórios."}]'::jsonb
)
on conflict (product_id) do nothing;

-- camera-termografica-bt-500b
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-500b',
  'Câmera Termográfica com Foco Automático e Laser 480x360 — BT-500B',
  'Câmera termográfica BT-500B com resolução 480x360, IFOV de 0,92 mrad, foco automático e medição de distância a laser até 40 m.
Lentes intercambiáveis de 6° a 48° com reconhecimento automático, tela touch de 5", anotação por voz e medição de -20°C a 410°C, com opcional até 2.000°C.',
  'Linha SC-B - Inspeção de Precisão', '/placeholder.svg',
  'Automático', '480x360', 'Distância até 40 m', '0,92 mrad (lente 24°)', true,
  'Câmera Termográfica Autofoco 480x360 BT-500B | Borotec',
  'Câmera termográfica BT-500B: 480x360, foco automático, laser até 40m, IFOV 0,92 mrad e lentes de 6° a 48°. Mais detalhe à distância. Peça orçamento!',
  '{"probe": "Resolução IR", "cable": "Foco", "camera": "Laser", "ip": "IFOV"}'::jsonb,
  now() + interval '1 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-500b',
  'A BT-500B é o modelo intermediário da Linha B, com cerca de 56% mais pixels térmicos que a BT-300B. Com resolução de 480x360, NETD <40mK e IFOV de 0,92 mrad, ela entrega mais detalhe em componentes pequenos e alvos distantes. O foco automático garante imagens nítidas em cada registro, e o laser mede a distância até o alvo em até 40 m, com o ponto exibido na imagem infravermelha. A lente padrão de 24° pode ser trocada pelas opcionais de 48°, 12° ou 6°, com reconhecimento automático. A tela touch de 5" com 800x480, a anotação por voz e os textos predefinidos agilizam a análise em campo e a produção de laudos.

Prefere foco manual e um equipamento mais leve? [Conheça a Linha A.](/termografia/linha-sc-a/inspecao-avancada)',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "480x360", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "Reconhecimento de lente", "value": "Automático após a troca"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "0,92 / 1,87 / 0,46 / 0,23 mrad", "filter": true, "filter_value": "0,92 mrad"}, {"label": "Foco", "value": "Automático, elétrico e manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,3 / 2 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo, adaptador AC ou carregador veicular"}, {"label": "Economia de energia", "value": "Modo de suspensão"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,23 kg (com bateria)"}, {"label": "Dimensões", "value": "279x135x147 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}, {"label": "Medição de distância a laser", "value": "Até 40 m"}, {"label": "Alinhamento do laser", "value": "Posição exibida automaticamente na imagem infravermelha"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "5\", legível sob sol, 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "Infravermelho, visível, PIP, fusão e IMIX"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}, {"label": "Anotação por voz", "value": "60 segundos, salva com a imagem"}, {"label": "Anotação de texto", "value": "Textos predefinidos, salvos com a imagem"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}, {"title": "Software", "icon_name": "Cpu", "rows": [{"label": "Software de análise", "value": "Windows 7 ou superior, com análise e geração de relatórios"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com foco automático e lentes de 12° e 6°.', 'Laudos Termográficos e Inspeções em Série: foco automático, distância medida a laser e anotação por voz agilizam inspeções com muitos pontos e a produção de laudos.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.']::text[],
  '[{"question": "Qual a diferença entre a BT-300B, a BT-500B e a BT-600B?", "answer": "A resolução. A BT-300B tem 384x288, a BT-500B tem 480x360 e a BT-600B tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Qual a diferença entre a Linha B e a Linha A?", "answer": "As resoluções e as lentes são as mesmas. A Linha B tem foco automático, medição de distância a laser até 40 m, reconhecimento automático de lente e anotação por voz e texto. A Linha A tem foco manual e é mais leve (1,09 kg contra 1,23 kg)."}, {"question": "Para que serve a medição de distância a laser?", "answer": "O laser mede a distância até o alvo em até 40 m e mostra o ponto medido na imagem infravermelha. Assim o técnico sabe exatamente onde e a que distância cada registro foi feito."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, com anotações de voz e texto, e acompanham software para Windows com análise e geração de relatórios."}]'::jsonb
)
on conflict (product_id) do nothing;

-- camera-termografica-bt-600b
insert into products (id, name, description, category, image_url, cable, probe, camera, ip, active, seo_title, seo_description, spec_labels, created_at)
values (
  'camera-termografica-bt-600b',
  'Câmera Termográfica de Alta Resolução 640x512 com Foco Automático e Laser — BT-600B',
  'Câmera termográfica BT-600B com alta resolução de 640x512, IFOV de 0,66 mrad, foco automático e medição de distância a laser até 40 m.
Com a lente opcional de 6°, chega a 0,16 mrad para alvos a longa distância. Tela touch de 5", anotação por voz e medição até 2.000°C (opcional).',
  'Linha SC-B - Inspeção de Precisão', '/placeholder.svg',
  'Automático', '640x512', 'Distância até 40 m', '0,66 mrad (lente 24°)', true,
  'Câmera Termográfica Autofoco 640x512 BT-600B | Borotec',
  'Câmera termográfica BT-600B: 640x512, foco automático, laser até 40m e IFOV 0,66 mrad para alvos a longa distância. Lentes de 6° a 48°. Peça orçamento!',
  '{"probe": "Resolução IR", "cable": "Foco", "camera": "Laser", "ip": "IFOV"}'::jsonb,
  now() + interval '2 second'
)
on conflict (id) do nothing;

insert into product_details (product_id, specs_description, specs_left, specs_right, applications, faqs)
values (
  'camera-termografica-bt-600b',
  'A BT-600B é o modelo topo da Linha B, para termografistas e equipes que precisam do máximo de detalhe com o mínimo de tempo em campo. Com 640x512 pixels, NETD <40mK e IFOV de 0,66 mrad na lente padrão, ela chega a 0,16 mrad com a lente opcional de 6°, o que permite medir com precisão isoladores, conexões e cabos em subestações e linhas de transmissão. O foco automático e o laser, que mede a distância até o alvo em até 40 m, deixam cada registro nítido e bem documentado. A câmera reconhece automaticamente a lente instalada, e a anotação por voz e os textos predefinidos ficam salvos com a imagem. Mede de -20°C a 410°C, com faixa opcional até 2.000°C, e tem proteção IP54.

Prefere foco manual e um equipamento mais leve? [Conheça a Linha A.](/termografia/linha-sc-a/inspecao-avancada)',
  '[{"title": "Detector e Óptica", "icon_name": "Eye", "rows": [{"label": "Tipo de detector", "value": "FPA não resfriado, VOx"}, {"label": "Resolução IR", "value": "640x512", "filter": true}, {"label": "Sensibilidade térmica (NETD)", "value": "<40mK (@30°C)", "filter": true, "filter_value": "<40mK"}, {"label": "Faixa espectral", "value": "8~14μm"}, {"label": "Lente padrão", "value": "24°"}, {"label": "Lentes opcionais", "value": "48°, 12° e 6°"}, {"label": "Reconhecimento de lente", "value": "Automático após a troca"}, {"label": "IFOV (24° / 48° / 12° / 6°)", "value": "0,66 / 1,39 / 0,33 / 0,16 mrad", "filter": true, "filter_value": "0,66 mrad"}, {"label": "Foco", "value": "Automático, elétrico e manual"}, {"label": "Distância focal mínima (24° / 48° / 12° / 6°)", "value": "0,15 / 0,15 / 0,3 / 2 m"}]}, {"title": "Medição de Temperatura", "icon_name": "Thermometer", "rows": [{"label": "Faixa do objeto", "value": "-20°C~+150°C (baixa) / 0°C~+410°C (média)", "filter": true, "filter_value": "-20°C a 410°C"}, {"label": "Faixa opcional", "value": "+300°C~+650°C / +300°C~+2.000°C / outras"}, {"label": "Precisão", "value": "±2°C ou ±2% da leitura"}]}, {"title": "Análise de Medição", "icon_name": "Ruler", "rows": [{"label": "Configurações de medição", "value": "Até 10 pontos, 10 áreas e 5 linhas simultâneos, com máx./mín./média"}, {"label": "Temp. máx./mín. da tela", "value": "Captura automática"}, {"label": "Zoom digital", "value": "1x, 2x, 4x, 8x"}, {"label": "Correção de emissividade", "value": "Automática, conforme valor informado"}, {"label": "Correção atmosférica", "value": "Automática, por distância, temperatura ambiente e umidade relativa"}, {"label": "Isotermas", "value": "Sim"}, {"label": "Alarme", "value": "Sonoro e luminoso, acima ou abaixo da temperatura definida"}]}, {"title": "Conectividade", "icon_name": "Plug2", "rows": [{"label": "Wi-Fi", "value": "Sim, com visualização das imagens do cartão SD"}, {"label": "Bluetooth", "value": "Sim, para fone de ouvido"}, {"label": "4G (opcional)", "value": "Transmissão em tempo real para celular e imagens em nuvem"}, {"label": "GPS (opcional)", "value": "Latitude e longitude na tela e nas imagens salvas"}, {"label": "Saída de vídeo", "value": "HDMI (micro HDMI)"}]}, {"title": "Alimentação", "icon_name": "Zap", "rows": [{"label": "Bateria", "value": "Lítio recarregável e removível"}, {"label": "Tensão", "value": "DC 12V"}, {"label": "Autonomia", "value": "Mais de 3 horas a 25°C"}, {"label": "Carregamento", "value": "Carregador duplo, adaptador AC ou carregador veicular"}, {"label": "Economia de energia", "value": "Modo de suspensão"}]}, {"title": "Dimensões e Peso", "icon_name": "Package", "rows": [{"label": "Peso", "value": "1,23 kg (com bateria)"}, {"label": "Dimensões", "value": "279x135x147 mm"}]}]'::jsonb,
  '[{"title": "Luz Visível", "icon_name": "Camera", "rows": [{"label": "Câmera digital", "value": "5MP com lanterna LED"}, {"label": "Mira laser", "value": "Sim"}, {"label": "Medição de distância a laser", "value": "Até 40 m"}, {"label": "Alinhamento do laser", "value": "Posição exibida automaticamente na imagem infravermelha"}]}, {"title": "Exibição de Imagem", "icon_name": "Monitor", "rows": [{"label": "Tela", "value": "5\", legível sob sol, 800x480"}, {"label": "Tela touch", "value": "Capacitiva"}, {"label": "Paletas de cor", "value": "10"}, {"label": "Modos de imagem", "value": "Infravermelho, visível, PIP, fusão e IMIX"}]}, {"title": "Gravação e Armazenamento", "icon_name": "Camera", "rows": [{"label": "Cartão de memória", "value": "SD de alta velocidade, 32 GB"}, {"label": "Imagem infravermelha", "value": ".jpg / .png com dados completos de temperatura"}, {"label": "Imagem visível", "value": ".jpg"}, {"label": "Vídeo infravermelho", "value": "H.264 ou vídeo radiométrico completo"}, {"label": "Anotação por voz", "value": "60 segundos, salva com a imagem"}, {"label": "Anotação de texto", "value": "Textos predefinidos, salvos com a imagem"}]}, {"title": "Parâmetros Ambientais", "icon_name": "Shield", "rows": [{"label": "Temperatura de operação", "value": "-20°C a 55°C"}, {"label": "Temperatura de armazenamento", "value": "-40°C a 70°C"}, {"label": "Umidade", "value": "≤95%, sem condensação"}, {"label": "Grau de proteção", "value": "IP54"}]}, {"title": "Software", "icon_name": "Cpu", "rows": [{"label": "Software de análise", "value": "Windows 7 ou superior, com análise e geração de relatórios"}]}]'::jsonb,
  array['Subestações e Linhas de Transmissão: inspeção de isoladores, conexões, chaves e barramentos à distância, com foco automático e lentes de 12° e 6°.', 'Laudos Termográficos e Inspeções em Série: foco automático, distância medida a laser e anotação por voz agilizam inspeções com muitos pontos e a produção de laudos.', 'Painéis e Instalações Elétricas: inspeção de quadros, disjuntores e conexões em ambientes fechados, com a lente padrão de 24° ou a grande angular de 48°.', 'Manutenção Preditiva Industrial: detecção de anomalias em motores, rolamentos, bombas e mancais antes de paradas não planejadas.', 'Processos de Alta Temperatura: monitoramento de fornos, caldeiras, refratários e siderurgia, com faixa opcional até 2.000°C.']::text[],
  '[{"question": "Qual a diferença entre a BT-300B, a BT-500B e a BT-600B?", "answer": "A resolução. A BT-300B tem 384x288, a BT-500B tem 480x360 e a BT-600B tem 640x512. Com a lente padrão, cada pixel cobre cerca de 1,3 cm, 0,9 cm e 0,66 cm a 10 metros, respectivamente. Quanto maior a resolução, menor o alvo que a câmera mede com precisão à distância."}, {"question": "Qual a diferença entre a Linha B e a Linha A?", "answer": "As resoluções e as lentes são as mesmas. A Linha B tem foco automático, medição de distância a laser até 40 m, reconhecimento automático de lente e anotação por voz e texto. A Linha A tem foco manual e é mais leve (1,09 kg contra 1,23 kg)."}, {"question": "Para que serve a medição de distância a laser?", "answer": "O laser mede a distância até o alvo em até 40 m e mostra o ponto medido na imagem infravermelha. Assim o técnico sabe exatamente onde e a que distância cada registro foi feito."}, {"question": "As câmeras medem temperaturas acima de 410°C?", "answer": "Sim, com a faixa opcional. A faixa padrão vai de -20°C a 410°C, e há opções de 300°C a 650°C e de 300°C a 2.000°C para fornos, caldeiras e siderurgia."}, {"question": "É possível gerar laudos termográficos?", "answer": "Sim. As câmeras salvam imagens e vídeos radiométricos com todos os dados de temperatura, com anotações de voz e texto, e acompanham software para Windows com análise e geração de relatórios."}]'::jsonb
)
on conflict (product_id) do nothing;

commit;
